[WIP] St2 architecture post
Mierdin/mierdin.github.io pull request #6
Opened 2017-04-12 22:33 UTC by Mierdin

Working on stackstorm architecture post. Very much a WIP, this will be a long post.

2017-04-19 22:28 UTC, m4dcoder requested changes

2017-04-19 22:28 UTC, m4dcoder commented on _posts/2017-04-17-stackstorm-architecture-components.markdown
> +If you're just getting started with Mistral and want to explore, you should start looking at the `mistral` tool. This is the primary mechanism for CLI interactions with Mistral, and it's one of the b
I would make this paragraph less relevant. I prefer user to use Mistral from StackStorm. The mistral CLI is only used for troubleshooting purposes and I don't recommend asking user to start exploring from there.  They should start exploring by running workflow directly from StackStorm.

2017-04-19 22:30 UTC, m4dcoder commented
Also, how about security?  How can Mistral be secured?  How does st2.action authenticate w/ StackStorm?

2017-07-15 22:08 UTC, Mierdin commented
Given my recent code activities, I have decided to do a separate post on Mistral, so I've removed the bulk of what was there. Thanks for the feedback thus far, I'll be sure to reflect it in that post (as well as this one where applicable)

2017-08-29 04:59 UTC, merged